- name: wget
  shell: wget https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz

- name: tar
  shell: tar xvf nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz nginx-prometheus-exporter

- name: Copy nginx-prometheus-exporter
  copy:
    src: "./nginx-prometheus-exporter"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
  ignore_errors: yes

- name: remove file
  file: 
    path: ./nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    state: absent

- name: remove file
  file: 
    path: ./nginx-prometheus-exporter
    state: absent

- name: Copy nginx-prometheus-exporter.service
  copy:
    src: "../files/nginx-prometheus-exporter.service"
    dest: /etc/systemd/system/
    mode: '0644'

- name: nginx-prometheus-exporter is running
  systemd:
    name: nginx-prometheus-exporter
    state: started
    daemon_reload: true
    enabled: true
  ignore_errors: yes